pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    parameters {
    
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select an action')
    }
    stages {                               
        stage('Init') {
            steps {
                sh 'cd 00-vpc'
                sh "terraform init --reconfigure'"
            }
        }
        stage('Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-credentials') {
                    sh 'cd 00-vpc'
                    sh "terraform plan -out=tfplan"

                }
            } 
        }
        // stage('Apply') {
        //      when {
        //         expression { env.GIT_BRANCH = 'origin/main'}
        //     }
        //     steps {
        //         sh "echo 'This is Deploying...'"
        //         // error "This is error in the Deploy stage"
        //     }
        // }
    
    }           
       

    post {
        always {
            echo 'This will always run'     
            deleteDir()
        }
        success {
            echo 'This will run only if the pipeline is successful'
        }
        failure {
            echo 'This will run only if the pipeline fails'
        }
        unstable {
            echo 'This will run only if the pipeline is unstable'
        }
    }
}