pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
    
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select terraform action')
    }
    stages {                               
        stage('Init and Plan') {
             steps {
                withAWS(region: 'us-east-1', credentials: 'aws-credentials') {
                    sh '''
                    cd 00-vpc
                    terraform init -reconfigure
                    terraform plan -out=tfplan
                    '''
                }
            } 
        }
    
        stage('Apply or Destroy') {
            input {
                message "Do you want to ${params.ACTION} the infrastructure?"
                ok 'Yes'
            }
          
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-credentials') {                 
                        sh """
                            cd 00-vpc
                           if [ ${params.ACTION} == 'apply' ]; 
                           then
                                terraform apply -auto-approve tfplan
                            elif [ ${params.ACTION} == 'destroy' ];
                            then
                                terraform destroy -auto-approve
                            fi
                        """
                    
                }
            } 
        } 
        stage('Trigger SG Pipeline') {
            steps {
                build job: '10-sg', parameters: [string(name: 'ACTION', value: "apply")]

            }
        }
                                
    }
       

    post {
        always {
            echo 'This will always run'     
            deleteDir()
        }
        success {
            echo 'This will run only if the pipeline is successful'
        }
        failure {
            echo 'This will run only if the pipeline fails'
        }
        unstable {
            echo 'This will run only if the pipeline is unstable'
        }
    }
}