pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
    
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select terraform action')
    }
    stages {                               
        stage('Init') {
            steps {
                sh '''
                    cd 00-vpc
                    terraform init --reconfigure
                '''
            }
        }
        stage('Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-credentials') {
                    sh 'cd 00-vpc'
                    sh "terraform plan -out=tfplan"

                }
            } 
        }
        // stage('Apply') {
        //      when {
        //         expression { params.ACTION == 'apply' }
        //     }
        //     steps {
        //         withAWS(region: 'us-east-1', credentials: 'aws-credentials') {
        //             sh ''' 
        //                cd 00-vpc
        //                terraform apply -auto-approve tfplan
        //             '''
        //         }
        //     } 
        // }
        // stage('Destroy') {
        //     when {
        //         expression { params.ACTION == 'destroy' }
        //     }
        //     steps {
        //         withAWS(region: 'us-east-1', credentials: 'aws-credentials') {
        //             sh '''
        //             cd 00-vpc
        //             terraform destroy -auto-approve
        //             '''
        //         }
        //     }
        // }
    
        
    }
       

    post {
        always {
            echo 'This will always run'     
            deleteDir()
        }
        success {
            echo 'This will run only if the pipeline is successful'
        }
        failure {
            echo 'This will run only if the pipeline fails'
        }
        unstable {
            echo 'This will run only if the pipeline is unstable'
        }
    }
}